src/Entity/People.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\OneToOne;
use Doctrine\ORM\Mapping\ManyToOne;
use Doctrine\ORM\Mapping\JoinColumn;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * People is a class in which we storage information about a human being,
 * like their address, their phone number, etc.
 *
 * @ORM\Table(name="people")
 * @ORM\Entity(repositoryClass="App\Repository\PeopleRepository")
 */
class People
{
    /**
     * A private ID used to identify the people.
     *
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * The user with which the people connect themselves to the application.
     *
     * @var \App\Entity\User
     *
     * @OneToOne(targetEntity="User", inversedBy="people")
     * @JoinColumn(name="user_id", referencedColumnName="id")
     */
    private $user;

    /**
     * A title used to refer to the people (e.G. Doctor, Mx, etc.)
     *
     * @ORM\ManyToOne(targetEntity="Denomination")
     * @ORM\JoinColumn(name="denomination_id", referencedColumnName="id", nullable=true)
     */
    private $denomination;

    /**
     * The first name of the people.
     *
     * @var string
     *
     * @ORM\Column(name="first_name", type="string", length=255)
     */
    private $firstName;

    /**
     * The last name of the people.
     *
     * @var string
     *
     * @ORM\Column(name="last_name", type="string", length=255)
     */
    private $lastName;

    /**
     * Year of the first contact of the people
     *
     * @var int
     *
     * @ORM\Column(name="first_contact_year", type="integer")
     */
    private $firstContactYear;

    /**
     * The email address of the people.
     *
     * @var string
     *
     * @ORM\Column(name="email_address", type="string", length=255, nullable=true)
     */
    private $emailAddress;

    /**
     * A boolean used to check if the people want to receive the newletter.
     *
     * @var boolean
     *
     * @ORM\Column(name="is_receiving_newsletter", type="boolean")
     */
    private $isReceivingNewsletter = false;

    /**
     * A boolean used to check if the people want to receive the newletter
     * by mail or by email (true for email, false for physical mail).
     *
     * @var boolean
     *
     * @ORM\Column(name="newsletter_dematerialization", type="boolean")
     */
    private $newsletterDematerialization = false;

    /**
     * The home phone number of the people.
     *
     * @var string
     *
     * @ORM\Column(name="home_phone_number", type="string", length=10, nullable=true)
     */
    private $homePhoneNumber;

    /**
     * The cell phone number of the people.
     *
     * @var string
     *
     * @ORM\Column(name="cell_phone_number", type="string", length=10, nullable=true)
     */
    private $cellPhoneNumber;

    /**
     * The work phone number of the people.
     *
     * @var string
     *
     * @ORM\Column(name="work_phone_number", type="string", length=10, nullable=true)
     */
    private $workPhoneNumber;

    /**
     * The fax number of the people.
     *
     * @var string
     *
     * @ORM\Column(name="work_fax_number", type="string", length=10, nullable=true)
     */
    private $workFaxNumber;

    /**
     * A big field used to store comments about the people.
     *
     * @var string
     *
     * @ORM\Column(name="observations", type="string", length=1000, nullable=true)
     */
    private $observations;

    /**
     * A big field used to store sensitive comments about the people.
     * It can only be accessed by users having the right responsabilities.
     *
     * @var string
     *
     * @ORM\Column(name="sensitive_observations", type="string", length=1000, nullable=true)
     */
    private $sensitiveObservations;

    /**
     * The list of all the update of the people.
     *
     * @var UserUpdater[]
     *
     * @ORM\OneToMany(targetEntity="UserUpdater", mappedBy="updater")
     */
    private $updaters;

    /**
     * The different addresses of the people.
     *
     * @var Address[]
     *
     * @ORM\ManyToMany(targetEntity="Address")
     * @ORM\JoinTable(
     *      name="people_addresses",
     *      joinColumns={@JoinColumn(name="people_id", referencedColumnName="id")},
     *      inverseJoinColumns={@JoinColumn(name="address_id", referencedColumnName="id")}
     * )
     */
    private $addresses;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\PeopleType", inversedBy="peoples", cascade={"persist"})
     * @ORM\JoinTable(
     *      name="peoples_people_types",
     *      joinColumns={@JoinColumn(name="people_id", referencedColumnName="id")},
     *      inverseJoinColumns={@JoinColumn(name="people_type_id", referencedColumnName="id")}
     * )
     */
    private $types;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Membership", inversedBy="members", cascade={"persist", "remove"})
     * @ORM\OrderBy({"date_start" = "DESC"})
     * @ORM\JoinTable(
     *      name="peoples_memberships",
     *      joinColumns={@JoinColumn(name="membership_id", referencedColumnName="id")},
     *      inverseJoinColumns={@JoinColumn(name="people_id", referencedColumnName="id")}
     * )
     */
    private $memberships;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Donation", mappedBy="donator", orphanRemoval=true)
     */
    private $donations;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Payment", mappedBy="payer", orphanRemoval=true)
     */
    private $payments;

    /**
     *
     */
    function __construct($id = -1, $user = NULL, $denomination = NULL, $firstName = NULL, $lastName = NULL)
    {
        $this->id = $id;
        $this->user = $user;
        $this->denomination = $denomination;
        $this->firstName = $firstName;
        $this->lastName = $lastName;
        $this->memberships = new ArrayCollection();
        $this->donations = new ArrayCollection();
        $this->firstContactYear = (int) date('Y');
    }

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Get the value of denomination
     */
    public function getDenomination(): ?Denomination
    {
        return $this->denomination;
    }

    /**
     * Set the value of denomination
     * @return User
     */
    public function setDenomination($denomination)
    {
        $this->denomination = $denomination;

        return $this;
    }

    /**
     * Get the value of firstName
     *
     * @return string
     */
    public function getFirstName()
    {
        return $this->firstName;
    }

    /**
     * Set the value of firstName
     *
     * @param string $firstName
     *
     * @return User
     */
    public function setFirstName(string $firstName)
    {
        $this->firstName = $firstName;

        return $this;
    }

    /**
     * Get the value of lastName
     *
     * @return string
     */
    public function getLastName()
    {
        return $this->lastName;
    }

    /**
     * Set the value of lastName
     *
     * @param string $lastName
     *
     * @return User
     */
    public function setLastName(string $lastName)
    {
        $this->lastName = $lastName;

        return $this;
    }

    /**
     * @return int
     */
    function getFirstContactYear(): int
    {
        return $this->firstContactYear;
    }

    /**
     * @param int $firstContactYear
     * @return \self
     */
    function setFirstContactYear(int $firstContactYear): self
    {
        $this->firstContactYear = $firstContactYear;
        return $this;
    }

    /**
     * Get the value of emailAddress
     *
     * @return string
     */
    public function getEmailAddress()
    {
        return $this->emailAddress;
    }

    /**
     * Set the value of emailAddress
     *
     * @param string $emailAddress
     *
     * @return User
     */
    public function setEmailAddress(string $emailAddress)
    {
        $this->emailAddress = $emailAddress;

        return $this;
    }

    /**
     * Get the value of isReceivingNewsletter
     *
     * @return bool
     */
    public function getIsReceivingNewsletter()
    {
        return $this->isReceivingNewsletter;
    }

    /**
     * Set the value of isReceivingNewsletter
     *
     * @param boolean $isReceivingNewsletter If the person receives the newsletter.
     *
     * @return People
     */
    public function setIsReceivingNewsletter(bool $isReceivingNewsletter)
    {
        $this->isReceivingNewsletter = $isReceivingNewsletter;

        return $this;
    }

    /**
     * Get the value of newsletterDematerialization
     *
     * @return boolean
     */
    public function getNewsletterDematerialization()
    {
        return $this->newsletterDematerialization;
    }

    /**
     * Set the value of newsletterDematerialization
     *
     * @param boolean $newsletterDematerialization Is the newsletter received by mail.
     *
     * @return People
     */
    public function setNewsletterDematerialization(bool $newsletterDematerialization)
    {
        $this->newsletterDematerialization = $newsletterDematerialization;

        return $this;
    }

    /**
     * Get the value of homePhoneNumber
     *
     * @return string
     */
    public function getHomePhoneNumber()
    {
        return $this->homePhoneNumber;
    }

    /**
     * Get the formated value of homePhoneNumber for display
     *
     * @return string
     */
    public function getDisplayHomePhoneNumber()
    {
        // Format phone number for display purpose
        $chunks = str_split($this->homePhoneNumber, 2);
        return implode(' ', $chunks);
    }

    /**
     * Set the value of homePhoneNumber

src/Form/PeopleType.php
<?php

namespace App\Form;

use App\Entity\Denomination;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TelType;
use Symfony\Component\Form\Extension\Core\Type\RadioType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Contracts\Translation\TranslatorInterface;

/**
 * Form with all user's infos
 */
class PeopleType extends AbstractType
{
    public $translator;

    public function __construct(TranslatorInterface $translator) {
        $this->translator = $translator;
    }

    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
                ->add('denomination', EntityType::class, [
                    // Looks for choices from this entity
                    'class' => Denomination::class,
                    // Uses the Responsibility.label property as the visible option string
                    'choice_label' => 'label',
                    'label' => $this->translator->trans('Dénomination'),
                    'multiple' => false,
                    'expanded' => false,
                    'placeholder' => $this->translator->trans('Aucune'),
                    'required' => true,
                    'choice_attr' => function($denomination)
                    {
                        return ['data-denomination-description' => $denomination->getLabel()];
                    },
                ])
                ->add('lastname', TextType::class, [
                    'label' => $this->translator->trans('Nom de famille'),
                    'required' => true
                ])
                ->add('firstname', TextType::class, [
                    'label' => $this->translator->trans('Prénom'),
                    'required' => true
                ])
                ->add('firstContactYear', IntegerType::class, [
                    'label' => $this->translator->trans('Année du premier contact avec cette personne'),
                    'required' => true,
                ])
                ->add('isContact', CheckboxType::class, [
                    'label' => $this->translator->trans('Cette personne est un contact'),
                    'required' => false,
                ])
                ->add('needHelp', CheckboxType::class, [
                    'label' => $this->translator->trans('Cette personne est en lien avec le Pôle Social'),
                    'required' => false,
                ])
                ->add('addresses', CollectionType::class, [
                    'label' => false,
                    'entry_type' => AddressType::class,
                    'entry_options' => ['label' => false],
                    'allow_add' => true,
                    'required' => false
                ])
                ->add('emailAddress', EmailType::class, [
                    'label' => $this->translator->trans('Adresse mail'),
                    'required' => false,
                    'empty_data' => '',
                ])
                ->add('isReceivingNewsletter', CheckboxType::class, [
                    'required' => false,
                    'label' => $this->translator->trans('Reçoit la newsletter')
                ])
                ->add('newsletterDematerialization', CheckboxType::class, [
                    'required' => false,
                    'label' => $this->translator->trans('Reçoit la newsletter au format dématérialisé (e-mail)')
                ])
                ->add('homePhoneNumber', TelType::class, [
                    'label' => $this->translator->trans('Téléphone fixe'),
                    'help' => $this->translator->trans('Les numéros doivent commencer par 01, 02, 03, 04, 05, 08 ou 09 et ne comporter que des chiffres'),
                    'required' => false
                ])
                ->add('cellPhoneNumber', TelType::class, [
                    'label' => $this->translator->trans('Téléphone portable'),
                    'help' => $this->translator->trans('Les numéros doivent commencer par 06 ou 07 et ne comporter que des chiffres'),
                    'required' => false
                ])
                ->add('workPhoneNumber', TelType::class, [
                    'label' => $this->translator->trans('Téléphone de travail'),
                    'help' => $this->translator->trans('Les numéros doivent commencer par 0 et ne comporter que des chiffres'),
                    'required' => false
                ])
                ->add('workFaxNumber', TelType::class, [
                    'label' => $this->translator->trans('Fax de travail'),
                    'help' => $this->translator->trans('Les numéros doivent commencer par 0 et ne comporter que des chiffres'),
                    'required' => false
                ])
                ->add('observations', TextareaType::class, [
                    'label' => $this->translator->trans('Observations'),
                    'required' => false
                ])
                ->add('sensitiveObservations', TextareaType::class, [
                    'label' => $this->translator->trans('Détails médicaux'),
                    'required' => false,
                    'empty_data' => ''
                ]);
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'App\FormDataObject\UpdatePeopleDataFDO'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'app_user';
    }

}

templates/People/partials/people_action_buttons.html.twig
{% if is_granted("ROLE_GESTION") %}
    <div class="row">
        <div class="col">
            <a
                {% if member is defined %}
                    href="{{ path('member_edit', { 'id': people.id }) }}"
                {% else %}
                    href="{{ path('people_edit', { 'id': people.id }) }}"
                {% endif %}
                class="btn btn-primary btn-block huge-button mb-4"
            >
                <div>Éditer ce profil</div>
                <div class="pt-2">
                    <i class="ri-edit-2-fill"></i>
                </div>
            </a>
            <a
                href="{{ path('donation_new', {'person-id': people.id}) }}"
                class="btn btn-primary btn-block huge-button mb-4"
            >
                <div>Enregistrer un don</div>
                <div class="pt-2">
                    <i class="ri-cash-line"></i>
                </div>
            </a>
            {% if not hasActiveMembership %}
                <a
                    href="{{ path('membership_create', {'person-id': people.id}) }}"
                    class="btn btn btn-primary btn-block huge-button"
                >
                    <div>Enregistrer une adhésion</div>
                    <div class="pt-2">
                        <i class="ri-inbox-archive-fill"></i>
                    </div>
                </a>
            {% else %}
                <button
                    class="btn btn-primary btn-block huge-button"
                    disabled="disabled"
                    data-toggle="tooltip"
                    title="Cette personne a déjà une adhésion active"
                >
                    <div>Enregistrer une adhésion</div>
                    <div class="pt-2">
                        <i class="ri-inbox-archive-fill"></i>
                    </div>
                </button>
            {% endif %}
        </div>
    </div>
{% endif %}

templates/People/partials/people_details_page.html.twig
<div class="row">
    <div class="col">
        <div class="bg-light p-4 mb-4">
            <h3 class="text-center">
                {% if people.denomination or people.firstname or people.lastname %}
                    {{ people.denomination ? people.denomination.label : "" }} {{ people.lastname|upper }} {{ people.firstname }}
                {% else %}
                    Ce·tte membre n'a pas de nom
                {% endif %}
            </h3>
            <div class="lead text-center">
                {% for type in people.types %}
                    {% if not type.isSensible or (type.isSensible and (is_granted('ROLE_GESTION_SENSIBLE') or is_granted('ROLE_ADMIN_SENSIBLE'))) %}
                        <span
                                class="badge badge-info"
                                data-toggle="tooltip"
                                title="{{ type.description }}"
                        >
                            {{ type.label }}
                        </span>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</div>

<div class="row mb-4">
    <div class="col-2">
        {{ include('People/partials/people_action_buttons.html.twig', { people: people, hasActiveMembership: hasActiveMembership }) }}
    </div>
    <div class="col">
        <div class="d-flex flex-column h-100">
            <div class="row mb-4">
                <div class="col">
                    <div class="bg-light p-4 h-100">
                        <h4 class="text-center mb-4">
                            Informations de contact
                        </h4>
                        <div class="row">
                            <div class="col text-center">
                                <strong>
                                    Adresse postale&nbsp;:
                                </strong>
                                <br>
                                {% if people.hasNoAddressDefined() %}
                                    <i>Ce membre n'a pas d'adresse enregistrée.</i>
                                {% else %}
                                    {% for address in people.addresses %}
                                        {{address.line}}
                                        <br>
                                        {% if not address.lineTwo is null %}
                                            {{ address.lineTwo }}<br>
                                        {% endif %}
                                        {{address.postalCode}}, {{address.city}}, {{address.country}}
                                    {% endfor %}
                                {% endif %}
                            </div>
                            <div class="col text-center">
                                <strong>
                                    Adresse mail&nbsp;:
                                </strong>
                                <br>
                                {{ people.emailAddress }}
                                {% if people.isReceivingNewsletter %}
                                    <span data-toggle="tooltip" title="Abonné-e à la newsletter" >
                                <i class="icon ion-md-paper"></i>
                            </span>
                                {% endif %}
                                {% if people.newsletterDematerialization %}
                                    <span data-toggle="tooltip" title="Newsletter envoyée sous format dématérialisé" >
                                <i class="icon ion-md-mail"></i>
                            </span>
                                {% endif %}
                            </div>
                            <div class="col-6">
                                <div class="row">
                                    <div class="col text-center mb-2">
                                        <strong>
                                            Téléphone fixe&nbsp;:
                                        </strong>
                                        <br>
                                        {{ people.displayHomePhoneNumber }}
                                    </div>
                                    <div class="col text-center">
                                        <strong>
                                            Téléphone professionnel&nbsp;:
                                        </strong>
                                        <br>
                                        {{ people.displayWorkPhoneNumber }}
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col text-center mb-2">
                                        <strong>
                                            Téléphone portable&nbsp;:
                                        </strong>
                                        <br>
                                        {{ people.displayCellPhoneNumber }}
                                    </div>
                                    <div class="col text-center">
                                        <strong>
                                            Fax&nbsp;:
                                        </strong>
                                        <br>
                                        {{ people.displayWorkFaxNumber }}
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
                <div class="col-4">
                    <div class="bg-light p-4 h-100">
                        <h4 class="text-center mb-4">
                            Autres informations
                        </h4>
                        <div class="row">
                            <div class="col-12 text-center">
                                <strong>
                                    Année de premier contact&nbsp;:
                                </strong>
                                {{ people.firstContactYear }}
                            </div>
                            <div class="col-12 text-center mt-2">
                                <strong>
                                    Observations&nbsp;:
                                </strong>
                                <br>
                                {{ people.observations}}
                            </div>
                            {% if is_granted("ROLE_GESTION_SENSIBLE") %}
                                <div class="col-12 text-center mt-2">
                                    <strong>
                                        Détails médicaux&nbsp;:
                                    </strong>
                                    <br>
                                    {{ people.sensitiveObservations }}
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            <div class="flex-grow-1">
                {{ include('People/partials/people_fiscal_receipt_generation.html.twig', { people: people }) }}
            </div>
        </div>
    </div>
</div>

<div class="row mb-4">
    <div class="col">
        {{ include('People/partials/people_payments_list.html.twig', { people: people }) }}
    </div>
</div>

<div class="row mb-4">
    <div class="col">
        {{ include('People/partials/people_memberships_list.html.twig', { people: people }) }}
    </div>
    <div class="col">
        {{ include('People/partials/people_donations_list.html.twig', { people: people }) }}
    </div>
</div>

templates/People/partials/people_donations_list.html.twig
{% block javascript %}
    {{ encore_entry_script_tags('people_donations_list') }}
{% endblock %}

<div class="row">
    <div class="col">
        <div class="bg-light p-4 mb-4">
            <h4 class="text-center mb-5">
                Tous les dons
            </h4>
            <table
                id="donations-list"
                class="table table-sm bg-white"
                data-ajax-url="/ajax/people/{{ people.id }}/list/donations">
                <thead class="border-bottom-0">
                    <tr>
                        <th scope="col" style="width: 15%">
                            Provenance
                        </th>
                        <th class="text-center" scope="col" style="width: 10%">
                            Prix
                        </th>
                        <th scope="col" style="width: 15%">
                            Date
                        </th>
                        <th class="text-center" scope="col" style="width: 15%">
                            Montant<br>du paiement
                        </th>
                        <th scope="col" style="width: 15%">
                            Réglé via
                        </th>
                        <th class="text-center" scope="col" style="width: 25%">
                            Commentaire
                        </th>
                        <th class="text-center" scope="col" style="width: 5%"></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                </tbody>
            </table>
            <div
                id="childrow-structure"
                class="d-none">
                <div class="container-fluid bg-white">
                    <div class="row">
                        <div class="col px-1">
                            <div class="text-center p-2">
                                <div class="row">
                                    <div id="payment-container" class="col align-self-stretch">
                                        <div class="bg-light py-2 h-100">
                                            <div class="mb-2">
                                                <strong>Paiement</strong>
                                            </div>
                                            <div id="paiement-information-container">
                                                Effectué par <span class="made-by"></span><br>
                                                Reçu le <span class="date-received"></span><br>
                                                Encaissé le <span class="date-cashed"></span>
                                            </div>
                                        </div>
                                    </div>
                                    <div id="fiscal-receipt-container" class="col align-self-stretch">
                                        <div class="bg-light py-2 h-100">
                                            <div class="mb-2">
                                                <strong>Reçu fiscal</strong>
                                            </div>
                                            <div id="fiscal-receipt-container">
                                                Année fiscale&nbsp;: <span class="fiscal-year"></span><br>
                                                Numéro d'ordre&nbsp;: <span class="order-code"></span><br>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row mt-4">
                                    <div class="col align-self-stretch">
                                        <div class="bg-light py-2 h-100">
                                            <div class="mb-2">
                                                <strong>Commentaire</strong>
                                            </div>
                                            <div id="comment-container" class="font-italic"></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>