src/Entity/Payment.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PaymentRepository")
 */
class Payment
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_received;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date_cashed;

    /**
     * @ORM\Column(type="float")
     */
    private $amount;

    /**
     * @ORM\Column(type="string", length=3000, nullable=true)
     */
    private $comment;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\PaymentType", inversedBy="payments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $type;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Membership", mappedBy="payment", cascade={"persist", "remove"})
     */
    private $membership;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Donation", mappedBy="payment")
     */
    private $donation;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\People", inversedBy="payments")
     */
    private $payer;

    /**
     * When the payment is made by check, save the check number
     * @ORM\Column(type="string", length=40, nullable=true)
     */
    private $check_number;

    /**
     * When the payment is made by check, save the bank
     * @ORM\ManyToOne(targetEntity="App\Entity\Bank", inversedBy="payments")
     */
    private $bank;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Receipt", mappedBy="payment", cascade={"persist", "remove"})
     */
    private $receipt;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateReceived(): ?\DateTimeInterface
    {
        return $this->date_received;
    }

    public function setDateReceived(?\DateTimeInterface $date_received): self
    {
        $this->date_received = $date_received;

        return $this;
    }

    public function getDateCashed(): ?\DateTimeInterface
    {
        return $this->date_cashed;
    }

    public function setDateCashed(?\DateTimeInterface $date_cashed): self
    {
        $this->date_cashed = $date_cashed;

        return $this;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    /**
     * Set the payment amount
     *
     * @param float $amount Must be greater than 0
     * @return \self
     * @throws \InvalidArgumentException
     */
    public function setAmount(float $amount): self
    {
        if ($amount <= 0)
        {
            throw new \InvalidArgumentException('The payment amount should be greater than 0');
        }

        $this->amount = $amount;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    public function getType(): ?PaymentType
    {
        return $this->type;
    }

    public function setType(?PaymentType $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getMembership(): ?Membership
    {
        return $this->membership;
    }

    public function setMembership(?Membership $membership): self
    {
        $this->membership = $membership;

        // set (or unset) the owning side of the relation if necessary
        $newPayment = $membership === null ? null : $this;
        if ($newPayment !== $membership->getPayment()) {
            $membership->setPayment($newPayment);
        }

        return $this;
    }

    function getPayer(): People
    {
        return $this->payer;
    }

    function setPayer($payer): self
    {
        $this->payer = $payer;


        return $this;
    }

    /**
     * @return Donation
     */
    public function getDonation(): ?Donation
    {
        return $this->donation;
    }

    public function setDonation(Donation $donation): self
    {
        $this->donation = $donation;

        // set (or unset) the owning side of the relation if necessary
        $newPayment = $donation === null ? null : $this;
        if ($newPayment !== $donation->getPayment()) {
            $donation->setPayment($newPayment);
        }

        return $this;
    }

    function getBank()
    {
        return $this->bank;
    }

    /**
     * Set Bank for this payment
     *
     * @param \App\Entity\Bank $bank Bank to set for this payment
     * @return \self
     * @throws \Exception If bank information is not needed in the
     *                    corresponding payment type, throws an exception
     */
    function setBank(?Bank $bank): self
    {
        if (!$this->type->isBankneeded() && !is_null($bank))
        {
            throw new \Exception('Bank information is not needed in this payment.');
        }
        $this->bank = $bank;

        return $this;
    }

    public function getReceipt(): ?Receipt
    {
        return $this->receipt;
    }

    public function setReceipt(Receipt $receipt): self
    {
        $this->receipt = $receipt;

        // set the owning side of the relation if necessary
        if ($receipt->getPayment() !== $this) {
            $receipt->setPayment($this);
        }

        return $this;
    }

    function getCheckNumber(): ?string
    {
        return $this->check_number;
    }

    function setCheckNumber($check_number): self
    {
        $this->check_number = $check_number;
        return $this;
    }
}

src/Controller/MembershipController.php
<?php

namespace App\Controller;

use App\Entity\People;
use App\Entity\Payment;
use App\Entity\Receipt;
use App\Entity\Donation;
use App\Entity\Membership;
use App\Entity\MembershipType;
use App\Entity\PaymentType;
use App\Form\MemberSelectionType;
use App\Form\MembershipFormType;

use App\FormDataObject\MemberSelectionFDO;
use App\FormDataObject\UpdateMembershipFDO;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Contracts\Translation\TranslatorInterface;

/**
 * MembershipController controller.
 *
 * @Route(path="/{_locale}/membership", requirements={"_locale"="en|fr"})
 */
class MembershipController extends AbstractController
{
    /**
     * @Route("/member-selection", name="member-selection")
     * @Security("is_granted('ROLE_GESTION')")
     */
    public function memberSelectionAction(Request $request)
    {
        $em = $this->getDoctrine()->getManager();

        $peoples = $em->getRepository(People::class)->findWithNoActiveMembership();

        $memberSelectionFDO = new MemberSelectionFDO();

        $memberSelectionForm = $this->createForm(MemberSelectionType::class, $memberSelectionFDO, [
            'peoples' => $peoples
        ]);

        $options = $memberSelectionForm->get('newMembers')->getConfig()->getOptions();
        $choices = $options['choices'];

        $memberSelectionForm->handleRequest($request);

        // Submit change
        if ($memberSelectionForm->isSubmitted() && $memberSelectionForm->isValid())
        {
            dump($memberSelectionFDO->getNewMembers());
            die();
        }

        return $this->render('Membership/member-selection.html.twig', [
            'peoples' => $choices,
            'member_selection_form' => $memberSelectionForm->createView()
        ]);
    }

    /**
     * Lists all memberships entities.
     * @return views
     * @Route(path="/", name="membership_list", methods={"GET"})
     * @Security("is_granted('ROLE_GESTION')")
     */
    public function listAction()
    {
        // Redirect for now, but we need to add a list of all memberships
        return $this->redirectToRoute('membership_active_list');
    }

    /**
     * Lists active memberships entities.
     * @return views
     * @Route(path="/active", name="membership_active_list", methods={"GET"})
     * @Security("is_granted('ROLE_GESTION')")
     */
    public function listActiveAction()
    {
        $em = $this->getDoctrine()->getManager();

        $members = $em->getRepository(People::class)->findWithActiveMembership();

        return $this->render('Membership/active_list.html.twig', array(
            'members' => $members,
        ));
    }

    /**
     * Lists past memberships entities.
     * @return views
     * @Route(path="/past", name="membership_past_list", methods={"GET"})
     * @Security("is_granted('ROLE_GESTION')")
     */
    public function listPastAction()
    {
        $em = $this->getDoctrine()->getManager();

        $members = $em->getRepository(People::class)->findAll();

        return $this->render('Membership/past_list.html.twig', array(
            'members' => $members,
        ));
    }

    /**
     * Create a new membership
     * @return views
     * @Route("/new", name="membership_create", methods={"GET", "POST"})
     * @Security("is_granted('ROLE_GESTION')")
     */
    public function createAction(Request $request, TranslatorInterface $translator)
    {
        // Form setup
        $em = $this->getDoctrine()->getManager();

        $peopleWithNoActiveMembership = $em->getRepository(People::class)->findWithNoActiveMembership();

        $updateMembershipFDO = new UpdateMembershipFDO();

        // Preselect donator if optional parameter is not null
        $personId = $request->get('person-id');

        if (!is_null($personId))
        {
            $newMember = $em->getRepository(People::class)->find($personId);

            if (is_null($newMember))
            {
                $this->addFlash(
                    'danger', 'La personne pré-sélectionnée n\'existe pas en base de donnée.'
                );
            }
            // We make sure that this person has no active membership
            else if (in_array($newMember, $peopleWithNoActiveMembership))
            {
                $updateMembershipFDO->setMembers([$newMember]);
                $updateMembershipFDO->setNewMember($newMember);

                $defaultMembership = $em->getRepository(MembershipType::class)->findBy([
                    'isMultiMembers' => 0
                ], null, 1)[0];
                $updateMembershipFDO->setMembershipType($defaultMembership);
            }
            else
            {
                $this->addFlash(
                    'danger', 'La personne pré-sélectionnée a déjà une adhésion active.'
                );
            }
        }

        // Preselect check payment type
        $checkPaymentType = $em->getRepository(PaymentType::class)->find(4);
        $updateMembershipFDO->setPaymentType($checkPaymentType);

        $membershipCreationForm = $this->createForm(MembershipFormType::class, $updateMembershipFDO, [
            'selectablePeople' => $peopleWithNoActiveMembership,
        ]);

        $membershipCreationForm->handleRequest($request);

        // Submit change
        if ($membershipCreationForm->isSubmitted() && $membershipCreationForm->isValid())
        {
            $fiscalYear = $updateMembershipFDO->getMembershipFiscalYear();

            // Membership
            $membership = new Membership();

            $membership->setMembers($updateMembershipFDO->getMembers());
            $membership->setType($updateMembershipFDO->getMembershipType());
            $membership->setAmount($updateMembershipFDO->getMembershipAmount());
            $membership->setDateStart($updateMembershipFDO->getMembershipDateStart());
            $membership->setDateEnd($updateMembershipFDO->getMembershipDateEnd());
            $membership->setFiscalYear($fiscalYear);
            $membership->setComment($updateMembershipFDO->getMembershipComment());

            // Payment
            $payment = new Payment();

            $payment->setType($updateMembershipFDO->getPaymentType());
            $payment->setAmount($updateMembershipFDO->getPaymentAmount());
            $payment->setDateReceived($updateMembershipFDO->getPaymentDateReceived());
            $payment->setDateCashed($updateMembershipFDO->getPaymentDateCashed());
            if ($payment->getType()->isBankneeded())
            {
                $payment->setBank($updateMembershipFDO->getBank());
                $payment->setCheckNumber($updateMembershipFDO->getCheckNumber());
            }
            else
            {
                $payment->setBank(null);
            }
            $payment->setPayer($updateMembershipFDO->getPayer());
            $payment->setMembership($membership);

            // Donation
            $donationAmount = $updateMembershipFDO->getDonationAmount();

            // If donation is also done with the membership
            if (!empty($donationAmount) && $donationAmount > 0) {
                $donation = new Donation();

                $donation->setAmount($donationAmount);
                $donation->setDonator($updateMembershipFDO->getPayer());
                $donation->setDonationDate($payment->getDateReceived());

                $payment->setDonation($donation);

                $em->persist($donation);
            }

            $em->persist($membership);
            $em->persist($payment);

            // Receipt
            $lastOrderNumber = $em->getRepository(Receipt::class)
                    ->findLastOrderNumberForAYear($fiscalYear);

            $receipt = new Receipt();

            $receipt->setPayment($payment);
            $receipt->setOrderNumber($lastOrderNumber + 1);

            $receipt->setYear($fiscalYear);
            $receipt->setOrderCode();

            $em->persist($receipt);

            $em->flush();

            $this->addFlash(
                'success', $translator->trans('L\'adhésion a bien été enregistrée.')
            );

            return $this->redirectToRoute('membership_show', array('id' => $membership->getId()));
        }

        return $this->render('Membership/new.html.twig', [
            'membership_creation_form' => $membershipCreationForm->createView()
        ]);
    }

    /**
     * Finds and displays the memberships of a people.
     * @return views
     * @param People $people The user to find to display memberships.
     * @Route("/{id}", name="membership_show", methods={"GET"})
     * @Security("is_granted('ROLE_GESTION') || (is_granted('ROLE_INSCRIT_E') && (user.getId() == id))")
     */
    public function showAction(Membership $membership)
    {
        return $this->render('Membership/show.html.twig', array(
            'membership' => $membership,
        ));
    }

    /**
     * Create a new membership
     * @return views
     * @Route("/{id}/edit", name="membership_edit", methods={"GET", "POST"})
     * @Security("is_granted('ROLE_GESTION')")
     */
    public function editAction(Membership $membership, Request $request, TranslatorInterface $translator)
    {
        // Form setup
        $em = $this->getDoctrine()->getManager();

        $peopleWithNoActiveMembership = $em->getRepository(People::class)->findWithNoActiveMembership();
        $oldMembers = $membership->getMembers()->toArray();
        $selectablePeople = array_merge($peopleWithNoActiveMembership, $oldMembers);

        $updateMembershipFDO = new UpdateMembershipFDO($membership);

        $membershipEditForm = $this->createForm(MembershipFormType::class, $updateMembershipFDO, [
            'selectablePeople' => $selectablePeople,
        ]);

templates/Membership/_delete_form_button.html.twig
<form
      method="post"
      action="{{ path('membership_delete', {'id': membership.id}) }}"
      >
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ membership.id) }}">
    <button type="submit" class="btn btn-danger" id="delete_button"><i class="ri-delete-bin-7-fill"></i>&nbsp;{% trans %}Supprimer{% endtrans %}</button>
</form>

templates/Membership/_menu_membership.html.twig
{% block body %}
    {% set show_membership = show_membership is defined ? show_membership : null %}
    {% set edit_membership = edit_membership is defined ? edit_membership : null %}

    <ul class="list-group">
        <a href="{{ path('membership_show', { 'id': membership.id }) }}"
           class="list-group-item list-group-item-action {{ show_membership }}"
           >
            {% trans %}Adhésion{% endtrans %}
        </a>
    </ul>
    <h4 class="mt-4">{% trans %}Édition{% endtrans %}</h4>
    <ul class="list-group">
        <a href="{{ path('membership_edit', { 'id': membership.id }) }}"
           class="list-group-item list-group-item-action {{ edit_membership }}"
           >
            <i class="ri-edit-2-fill"></i>&nbsp;{% trans %}Adhésion{% endtrans %}
        </a>
    </ul>
{% endblock %}

templates/Membership/_people-placeholder.html.twig
<div class="col-md-6 mt-3 people-placeholder">
    <div class="border border-dashed p-3 h-100">
        <div class="row h-100">
            <div class="col-3">
                <img class="img-thumbnail" src="{{ asset('images/placeholder-personne.jpg') }}" alt="Profile photo placeholder">
            </div>
            <div class="col h-100 d-flex align-items-center justify-content-center">
                <span class="font-italic text-muted">{% trans %}Choisissez un autre membre{% endtrans %}</span>
            </div>
        </div>
    </div>
</div>

templates/Membership/_row.html.twig
<tr>
    <td class="align-middle text-uppercase">{{ member.lastname }}</td>
    <td class="align-middle">{{ member.firstname }}</td>
    <td class="align-middle text-center">{{ membership.payment.receipt.orderCode }}</td>
    <td class="align-middle text-center">
        {% trans %}Du{% endtrans %} {{ membership.getDateStart | date('d M. Y') }}
        <br>
        {% trans %}au{% endtrans %} {{ membership.getDateEnd | date('d M. Y') }}
    </td>
    <td class="align-middle text-center">
        {{ membership.type.label }}
    </td>
    <td class="align-middle text-center">
        {{ membership.type.defaultAmount }}&nbsp;€
    </td>
    <td class="align-middle text-center">
        {{ membership.payment.type.label }}
    </td>
    <td class="align-middle text-center" data-sort="{{ membership.payment.dateCashed | date('Ymd') }}">
        {% if membership.payment.dateCashed is null %}
            <span class=""><i class="icon ion-md-warning"></i> {% trans %}Pas encore encaissé{% endtrans %}</span>
        {% else %}
            {{ membership.payment.dateCashed | date('d M. Y') }}
        {% endif %}
    </td>
    <td class="align-middle column-action">
        <a
            href="{{ path('membership_show', { 'id': membership.id }) }}"
            class="btn btn-secondary"
            data-toggle="tooltip"
            title="{% trans %}Voir les détails de l'adhésion{% endtrans %}"
            >
            <i class="icon ion-md-eye"></i>
        </a>
    </td>
    <td class="align-middle column-action">
        <a
            href="{{ path('membership_edit', { 'id': membership.id }) }}"
            class="btn btn-secondary"
            data-toggle="tooltip"
            title="{% trans %}Éditer l'adhésion{% endtrans %}"
            >
            <i class="icon ion-md-create"></i>
        </a>
    </td>
</tr>

templates/Membership/people-placeholder.html.twig
<div class="col-md-6 mt-3 people-placeholder">
    <div class="border border-dashed p-3 h-100">
        <div class="row h-100">
            <div class="col-3">
                <img class="img-thumbnail" src="{{ asset('images/placeholder-personne.jpg') }}" alt="Profile photo placeholder">
            </div>
            <div class="col h-100 d-flex align-items-center justify-content-center">
                <span class="font-italic text-muted">{% trans %}Choisissez un autre membre{% endtrans %}</span>
            </div>
        </div>
    </div>
</div>

templates/Membership/show.html.twig
{% extends 'Home/base.html.twig' %}

{% block title %}
    {% trans %}Adhésion du{% endtrans %} {{ membership.getDateStart | date('d M. Y') }}
    {% trans %}au{% endtrans %} {{ membership.getDateEnd | date('d M. Y') }}
{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/User/show.css') }}">
    <link rel="stylesheet" href="{{ asset('css/Membership/common.css') }}">
{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item">
        <a href="/">{% trans %}Accueil{% endtrans %}</a>
    </li>
    {% if is_granted("ROLE_GESTION") %}
    <li class="breadcrumb-item">
        <a href="{{ path('membership_active_list') }}">{% trans %}Adhésions{% endtrans %}</a>
    </li>
    {% endif %}
    <li class="breadcrumb-item active" aria-current="page">
        {% trans %}Adhésion du{% endtrans %} {{ membership.getDateStart | date('d M. Y') }}
        {% trans %}au{% endtrans %} {{ membership.getDateEnd | date('d M. Y') }}
    </li>
{% endblock %}

{% block body %}
    <br>
    <div class="container">
        <div class="row">
            <div class="col-8 col-md-2">
                {{ include('Membership/_menu_membership.html.twig', { show_membership: 'active' }) }}
            </div>
            <div class="col-12 col-md-10">
                <div class="row">
                    <div class="col-12">
                        <div class="bg-light p-4 mb-4">
                            <h3 class="text-center">
                                {% trans %}Adhésion{% endtrans %}
                                <span class="text-lowercase">{{ membership.type.label }}</span>
                                ({{ membership.type.defaultAmount }}&nbsp;€)
                            </h3>
                            <div class="text-center text-muted font-weight-light font-italic mb-2">
                                {{ membership.type.description }}
                            </div>
                            <div class="lead text-center">
                                valable du
                                {{ membership.getDateStart | localizeddate('long', 'none') }}
                                au
                                {{ membership.getDateEnd | localizeddate('long', 'none') }}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <div class="bg-light p-4 mb-4">
                            <h4 class="text-center">
                                {% if membership.members | length > 1 %}
                                    Membres
                                {% else %}
                                    Membre
                                {% endif %}
                            </h4>
                            <div class="row">
                                {% for member in membership.members %}
                                    {% include 'People/_people-summary.html.twig' with {'people': member} %}
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <div class="bg-light p-4 mb-4">
                            <h4 class="text-center">
                                Paiement
                            </h4>
                            <div class="lead text-center mb-4">
                                {% if membership.payment.dateCashed is null %}
                                    <i class="icon ion-md-warning text-info"></i>&nbsp;Paiement pas encore encaissé
                                {% else %}
                                    Encaissé le {{ membership.payment.dateCashed | localizeddate('long', 'none') }}
                                {% endif %}
                            </div>
                            <div class="row">
                                <div class="col text-center">
                                    <h5>
                                        Montant&nbsp;:
                                        {{ membership.payment.amount }}&nbsp;€
                                    </h5>
                                </div>
                                <div class="col text-center">
                                    <h5>
                                        Reçu le&nbsp;:
                                        {{ membership.payment.dateReceived | localizeddate('long', 'none') }}
                                    </h5>
                                </div>
                            </div>
                            <div class="row mt-3">
                                <div class="col text-center">
                                    <h5 class="mb-0">
                                        Effectué par&nbsp;:
                                    </h5>
                                    <div class="row">
                                        {% include 'People/_people-summary.html.twig' with {'people': membership.payment.payer} %}
                                    </div>
                                </div>
                                <div class="col">
                                    <h5 class="mb-0 text-center">
                                        Réglé via&nbsp;:
                                        {{ membership.payment.type.label }}
                                    </h5>
                                    {% if (membership.payment.type.isBankNeeded) %}
                                        {% include 'Payment/_check-summary.html.twig' with {'payment': membership.payment} %}
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <div class="bg-light p-4 mb-4">
                            <h4 class="text-center">
                                Reçu fiscal
                            </h4>
                            <div class="row">
                                <div class="col text-center">
                                    <h5>
                                        Année fiscale&nbsp;:
                                        {{ membership.payment.receipt.year }}
                                    </h5>
                                </div>
                                <div class="col text-center">
                                    <h5>
                                        Numéro d'ordre&nbsp;:
                                        {{ membership.payment.receipt.orderCode }}
                                    </h5>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% if membership.payment.donation is not null %}
                    <div class="row">
                        <div class="col-12">
                            <div class="bg-light p-4 mb-4">
                                <h4 class="text-center mb-4">
                                    Un don de {{ membership.payment.donation.amount }}&nbsp;€ est lié à cette adhésion
                                </h4>
                                <div>
                                    <a class="btn btn-block btn-lg btn-primary"
                                        href="{{ path('donation_show', { 'id': membership.payment.donation.id }) }}"
                                        >
                                        {% trans %}Voir le don{% endtrans %}
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
                <div class="row">
                    <div class="col-12">
                        <div class="bg-light p-4 mb-4">
                            <h4 class="text-center">
                                Commentaire
                            </h4>
                            <div class="row">
                                <div class="col">
                                    {% if membership.comment != '' %}
                                        {{ membership.comment }}
                                    {% else  %}
                                        <div class="text-center">
                                            <span class="text-italic text-muted">
                                                Pas de commentaire.
                                            </span>
                                        </div>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <br>
                <div class="row">
                    {% if is_granted("ROLE_GESTION") %}
                    <div class="col">
                        <a href="{{ path('membership_active_list') }}" class="btn btn-secondary"><i class="icon ion-md-arrow-back"></i>&nbsp;{% trans %}Retourner à la liste des adhésions actives{% endtrans %}</a>
                    </div>
                    {% endif %}
                    <div class="col text-right">
                        <button data-toggle="modal" data-target="#confirmation-modal-deletion-membership-{{ membership.id }}" class="btn btn-danger">
                            <i class="icon ion-md-trash"></i>&nbsp;{% trans %}Supprimer l'adhésion{% endtrans %}
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="confirmation-modal-deletion-membership-{{ membership.id }}" class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-body">
                    <p>
                        {% trans %}Souhaitez-vous réellement supprimer cette adhésion&nbsp;?{% endtrans %}
                    </p>
                    <div class="alert alert-warning" role="alert">
                        <i class="icon ion-md-alert"></i>&nbsp;{% trans %}Les données seront supprimées de manière définitive.{% endtrans %}
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="col">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal"><i class="icon ion-md-arrow-back"></i>&nbsp;{% trans %}Annuler{% endtrans %}</button>
                    </div>
                    <div class="col text-right">
                        {{ include('Membership/_delete_form_button.html.twig') }}
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}